### ISSUE TITLE
ds() not defined

### ISSUE THREAD

**Issue by mortenscheel** [laradumps/global-laradumps#1]
Is the global laradumps installation supposed to provide the `ds()` function globally?
I've confirmed that the phar file is being included, but `function_exists('ds')` returns false.

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/laradumps/global-laradumps/releases/tag/v1.1.1

Can you try again?

**Comment by mortenscheel** [comment]
Now ds() is defined, but I get this when I run it:
```
Call to undefined function LaraDumpsCore\LaraDumps\LaraDumpsCore\Actions\runningInTest()
```
