### ISSUE TITLE
Uninstall Command Broken

### ISSUE THREAD

**Issue by fahadkhan1740** [laradumps/global-laradumps#4]
The uninstall command is completely broken. It crashed my composer completely and I am unable to run any projects now.

I am using Laravel Herd and the composer was installed using that only.

```
composer

Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Failed opening required '/Users/fkhan/.composer/vendor/laradumps/global-laradumps/src/scripts/global-laradumps-loader.php' (include_path='.:') in Unknown on line 0
```

**Comment by luanfreitasdev** [comment]
Hello!

In your php.ini file, set `auto_prepend_file =` (empty) . This will solve the problem for other projects, but I will investigate this bug
